### ISSUE TITLE
正常更新下载update-center.json，但是无法安装插件 unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by go3k** [jenkins-zh/update-center-mirror#14]
根据社区论坛的方法，替换国内源地址为 https://updates.jenkins-zh.cn/update-center.json 并且本地放置好证书。
设置完毕点击 Check now 可以正常完成，不报错。
但是安装插件还是如下报错：我甚至把证书打包到jre的cacerts，没有效果。请问该如何解决？具体是什么原因？

```sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
Caused: sun.security.validator.ValidatorException: PKIX path building failed
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
Caused: javax.net.ssl.SSLHandshakeException
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2943)
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
	at java.net.URLConnection.getContentLength(URLConnection.java:485)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:398)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1242)
Caused: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1258)
Caused: java.io.IOException: Failed to load https://updates.jenkins.io/download/plugins/ant/1.11/ant.hpi?provider=tsinghua to /Users/builder2018/jenkins/jenkins-data/plugins/ant.jpi.tmp
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1265)
Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/ant/1.11/ant.hpi?provider=tsinghua
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1299)
	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1847)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2125)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1821)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by go3k** [comment]
从下午折腾到晚上总算是搞明白了，首先参考下面链接中的回答。
https://stackoverflow.com/a/47316409

问题原因大概(不好意思没细究概念)是：本地java环境不信任服务器的证书，我们要做的就是获得服务器的证书，然后再添加到JRE的cacerts keystore里面。具体操作命令so地址里面都有写。说说我的过程：

先添加了这个地址`https://updates.jenkins.io`的证书，还是不行，但是看报错发现重定向到了 `https://get.jenkins.io`继续添加这个证书，然后就可以正常安装插件了。

> 这两个地址的证书我看都是根证书机构认证的，但是我的java环境就行不信任，也不知道是为什么。

具体步骤：(Mac)
1. 例如报错：Failed to download from https://updates.jenkins.io/download/plugins/an... Safari浏览器中打开该地址，点击小锁头查看证书，把证书图标拖动到Finder即可保存。
2. keytool -import -alias $ALIAS -keystore $JavaHome/jre/lib/security/cacerts -file $cer_file 使用这个命令，ALIAS 是自己取的别名，cer_file是刚才下载的证书。jre keystore默认密码 changeit
3. 重启Jenkins

**Comment by LinuxSuRen** [comment]
部分 Java 的发行版本中携带的证书是不太相同的，感谢给出了解决问题的链接。
